---
title: "Lab 3 Writing Assignment"
subtitle: Electrical Schematics and Equations
---

## Writing Assignment

In this writing assignment you will learn to make high quality electrical schematics and equations.
You'll then write text to describe the operation of each circuit and how equations were used to specify component values.

## Statement of Work

Prepare high-quality electrical schematics and a set of equations to include in a methods section of a technical memo describing the the circuits you built in Lab 3.
You should include three schematics for your inverting offset amplifier, your 555 timer circuit, and your transimpedance amplifier. You should also include the equations you used to calculate component values for each circuit.
The accompanying text should describe what each circuit does, how the circuit works, and how the circuit schematics and associated equations can be used to choose components and specify their values.

An electrical schematic describes the functional connection of the components in an electrical circuit.
It **does not** directly represent the physical layout of the circuit in 3d-space on a breadboard or printed circuit board.
However, there are certain conventions you should follow when drawing your schematic to allow it to be easily read and understood.
These are detailed in the lab submission sheet and the specs below.

For this assignment, draw schematics for the inverting offset amplifier, the 555 timer circuit, and the transimpedance amplifier you built in Lab 3. After each schematic, include a 100-150 word section of text to describe its design and operation.

You must also include the equations you used to calculate all specified resistance values in your text. Reference them properly as “Equation 1” or "Eq. 1" not “eq 1” or any other way, and be sure to include units wherever appropriate. Units should not be italicized.

Ensure your schematics and equations follow all the proper conventions as detailed in the specs below and in the lab manual.

## Learning Objectives

By the end of this writing assignment you will...

- Draw neat and complete electrical schematics.
- Format and present equations in text
- Write text to reference the schematic and equations to explain the choices of circuit components and values.

## Required Resources

- [ ] Source for a schematic of the inverting offset amplifier circuit and equations used to calculate components used in lab.
- [ ] Source for a schematic of the 555 timer circuit and equations used to calculate components used in lab.
- [ ] Source for a schematic of the transimpedance amplifier circuit and equations used to calculate components used in lab.

## Specifications

### Effort

- [ ] Three electrical schematics are present.
- [ ] Text is present explaining the function of each circuit.
- [ ] Associated equations are present.
- [ ] Text is present explaining how the equations are used in circuit design.

### Completion

#### Electrical Schematics

- [ ] Standard electrical schematic symbols are used whenever possible (i.e., don't make up new symbols for resistors, amplifiers, etc.)
- [ ] All lines connecting elements are straight lines wherever possible (i.e., no curved lines)
- [ ] All junctions indicated with a solid circle at the intersection point
- [ ] No 4-way wire junctions
- [ ] Use line weights and fonts that are clearly visible.
- [ ] Reference designators and the values for parts are placed nearby the parts.
- [ ] Draw pins according to function (i.e., not just according to the physical layout of the pins on the chip.)
- [ ] All pins labeled with number
- [ ] All pins labeled with name/description of function
- [ ] Decoupling capacitors are placed nearby the part that they accompany.
- [ ] If needed, notes are legible and well-placed

#### Equations

-   [ ] Contain a label that numbers each equation 
-   [ ] Each equation is referenced in the text
-   [ ] Variables of the equations are described in the text and match those used in circuit schematics
-   [ ] Refer to appropriate op amp background covered in lectures where appropriate, don’t reinvent every wheel

#### Supporting Text

- [ ] Refers to each schematic/equation.
- [ ] Correct sentence mechanics like cohesion and coherence between sentences and no run-ons.
- [ ] Correct paragraph mechanics like topic sentences and placement at breaks between ideas.
- [ ] Language is not stilted and jargon is kept to a reasonable minimum.

## Resources

-   This University of Missouri website is a great reference for writing equations: “[Technical Communications Toolbox: Equations](https://engineering.missouri.edu/tech-toolbox/equations/)”.
-   Pages 4-8 of the “[User’s Guide for the `amsmath` Package](https://texdoc.org/serve/amsldoc.pdf/0)"