---
title: "Lectures"
---

Lecture content is delivered by videos.
Each week you will be expected to watch a set of videos and then take a multiple-choice quiz on the material.
Links to the videos and supplemental material are provided below.  All quizzes can be found on Canvas.
The slides for the two whole-class meetings are also provided.

Note that in weeks 6 and 7, the order of Lectures/quiz/Lab are not the same for everyone. 
Please make sure prelab is done for the correct lab.

Quizzes are due at noon (12 p.m.) on Mondays on Canvas during the first half of the semester.  See Canvas for the exact dates.

# Week 1: E80 Kickoff meeting

- [Kickoff Slides](../presentation/kickoff/kickoff-presentation.qmd){target="_blank"}
- [Team Contract Guidelines](../presentation/kickoff/team-contract-guidelines.qmd){target="_blank"}
- [Team Contract Template](../presentation/kickoff/team-contract-template.qmd){target="_blank"}

# Week 2: Statistics for Experiments

- [Basic Statistics for Experiments Videos](https://www.youtube.com/watch?v=ywIUp9uNmY8&list=PLDA3QBjykWVxlOIHkdFEiuaXp-02mt8VI){target="_blank"}
- [Basic Statistics for Experiments Slides](/lectures/SLIDES_20180718_01_IntroAndBasics.pdf){target="_blank"}
- [Basics Statistics Example Spreadsheet](https://docs.google.com/spreadsheets/d/1vX6A31pxA10KfnWXvVotVhlXlFhyXyB6btyzb5Xk4xo/edit?usp=sharing){target="_blank"}
- [Basics Statistics Example MATLAB](https://drive.google.com/open?id=1g59Dyz9PjarGOT66BUw4t11QvD0FXfd_){target="_blank"}
- [All Statistics Summary Document](https://drive.google.com/open?id=1vHS10FuGOs_IwQG8Uzs9UoeD4REUTOl4){target="_blank"}
- [Student's t Values Table](https://drive.google.com/open?id=1dIRZvSaYBFEqbXAem_nys0N5lmKA2c1V){target="_blank"}

# Week 3: Basics of Electrical Measurements
- [Basics of Electrical Measurements Videos](https://www.youtube.com/playlist?list=PLDA3QBjykWVyDDmjCt-UFhZb8Ok0Ajfby){target="_blank"}
- [Basics of Electrical Measurements Slides](https://drive.google.com/file/d/1-4SoZdgNXmHkrtf45DcGWNuDbROOCEW9/view?usp=sharing){target="_blank"}
- [Error Propagation Video](https://www.youtube.com/watch?v=DiOs64kzSQw){target="_blank"}
- [Error Propagation Slides](/lectures/SLIDES_20180718_01_ErrorPropagation.pdf){target="_blank"}
- [Additional Information on Calculating Error in Multimeter Measurements](https://www.designworldonline.com/how-to-determine-digital-multimeter-accuracy/){target="_blank"}
- [Auntie Spark's Guide to breadboards](/lectures/AuntieSparksGuideToBreadboarding.pdf){target="_blank"}
- We also recommend watching videos 1 & 2 of next week's op-amp videos.

# Week 4: Operational Amplifiers
- [Operational Amplifiers Videos](https://www.youtube.com/playlist?list=PLDA3QBjykWVwctzkMzqvbLcZr3iyS85Hu){target="_blank"}
- [Operational Amplifiers Slides](https://drive.google.com/drive/folders/1j97hAUQ1RnWEw6dwOQ7hg6TDK5-3Y0pe?usp=sharing){target="_blank"}
- [Linear Regression Videos](https://www.youtube.com/watch?v=HsZhQyhg0tk&list=PLDA3QBjykWVxfuWGJPkS_O1xrhW9txOKt&index=1){target="_blank"}
- [Linear Regression Slides](/lectures/SLIDES_20180720_01_Linear_Regression.pdf){target="_blank"}
- [Linear Regression Example Spreadsheet](https://drive.google.com/open?id=1DUaiPw9Wgt_O8O7Mq5RMC3HpRIXVWgbr){target="_blank"}
- [Linear Regression Example MATLAB](https://drive.google.com/open?id=1eOS0lIQpyriTde-x_eN0lET-ya3I51Si){target="_blank"}
- [Additional Information on Op Amp impedance](https://www.electronics-notes.com/articles/analogue_circuits/operational-amplifier-op-amp/input-impedance.php){target="_blank"}

# Week 5: Temperature Measurements
- [Temperature Measurements Videos](https://www.youtube.com/playlist?list=PLDA3QBjykWVycTireTaEG8Fim4GnFEBpz){target="_blank"}
- [Temperature Measurements Slides](https://drive.google.com/drive/folders/1xC09jM35sX2pIvMsqE0E8lO8F7CKePlt?usp=sharing){target="_blank"}
- [Nonlinear Regresssion Video](https://www.youtube.com/watch?v=aE4W-JYnGgQ){target="_blank"}
- [Steinhart-hart-fitting.m](https://drive.google.com/open?id=19N-lH7GH1XP0PHImxZM9N5_MRfb8FWuX){target="_blank"}

# Week 6: Rotation Week 1
| Odd Teams, e.g.: 21 | Even Teams, e.g.: 22 |
|---------------------|----------------------|
| [Underwater Acoustics](https://www.youtube.com/playlist?list=PLDA3QBjykWVxF4HfyhYxnD4eD31wZkSvq){target="_blank"} | [Fluid Mechanics](https://www.youtube.com/playlist?list=PLDA3QBjykWVxFbfz1bAygXNHX5IJ4_vRi){target="_blank"} |
| [Slides](https://drive.google.com/drive/folders/1wlyxBH7Qco0LvU1Riqz3nqfAVviCSh8Q?usp=sharing){target="_blank"} | [Slides](https://drive.google.com/open?id=1FSzWEEap-6UiNJplJt5-_KHzOAAomzfk){target="_blank"} |

# Week 7: Rotation Week 2
| Odd Teams, e.g.: 21 | Even Teams, e.g.: 22 |
|---------------------|----------------------|
| [Fluid Mechanics](https://www.youtube.com/playlist?list=PLDA3QBjykWVxFbfz1bAygXNHX5IJ4_vRi){target="_blank"} | [Underwater Acoustics](https://www.youtube.com/playlist?list=PLDA3QBjykWVxF4HfyhYxnD4eD31wZkSvq){target="_blank"} | 
| [Slides](https://drive.google.com/open?id=1FSzWEEap-6UiNJplJt5-_KHzOAAomzfk){target="_blank"} | [Slides](https://drive.google.com/drive/folders/1wlyxBH7Qco0LvU1Riqz3nqfAVviCSh8Q?usp=sharing){target="_blank"} |

# Project Kickoff Meeting
- [Project Kickoff Slides](/presentation/project/project-presentation.qmd){target="_blank"}
- [Abstract Writing Assignment](/presentation/project/abstract-writing-assignment.qmd){target="_blank"}
- [Proposal Template](/project/proposal/template.qmd){target="_blank"}
- [Proposal Specifications](/project/proposal/submission.qmd){target="_blank"}

# Project Jump Start: Autonomous Navigation
- [Autonomous Navigation](https://www.youtube.com/playlist?list=PLDA3QBjykWVw9UDHYpLBnloHrAwpZyTbb){target="_blank"}
- [Autonomous Navigation Slides](https://drive.google.com/drive/folders/1yCA0z3uEAt4LO61vuYCOluFFPgQTbqYP?usp=sharing){target="_blank"}
- [Statistics of Integrals and Derivatives Video 1](https://www.youtube.com/watch?v=_0AcGK7asfM){target="_blank"}
- [Statistics of Integrals and Derivatives Video 2](https://www.youtube.com/watch?v=ej9O5ncO1iw){target="_blank"}
- [Statistics of Integrals and Derivatives Slides](/lectures/SLIDES_20190117_01_TimeSeriesErrors.pdf){target="_blank"}
- [Statistics of Integrals and Derivatives Accelerometer MATLAB Example](https://drive.google.com/open?id=1-jiIeGnTGc0ZuzfWS1xRK-mnt1NesF_Q){target="_blank"}
- [Statistics of Integrals and Derivatives Numerical Derivation Statistics MATLAB Demo.](https://drive.google.com/open?id=1uA-uhLO4cLXOAFCiALvTtgRjT2nDUVXY){target="_blank"}

# Supplementary Information
We have also included slides from topics covered in previous versions of E80 for additional reading if you are interested:

- [Fourier Series](https://drive.google.com/open?id=13HKwMvY7HrnMlP7yxZ-RZcRPDnSwaXov){target="_blank"}
- [DFTs and FFTs](https://drive.google.com/open?id=1e0OLo6uCw93evjV2mPyVCebRI_B46eTQ){target="_blank"}
- [Sampling, Aliasing, Folding](https://drive.google.com/open?id=1_lF1ZG382AHKLyA6_Bf0VBN1UHlD-eh_){target="_blank"}
- [ Dynamic Modeling](https://drive.google.com/open?id=1HM1sUSPzXYWta1Jq0z2ShTsH48vl-295){target="_blank"}, [[Wang Thesis](https://drive.google.com/open?id=1LOth9W0bl4DNe2W_82wve_ImHHN_F4E2){target="_blank"}], [[LabVIEW Model](https://drive.google.com/open?id=1fRpKLNxEBib_75muxPtMDq93WI87ORbK){target="_blank"}]
- [Introduction to E80 Robot Software](https://drive.google.com/open?id=1iZiWU3SrHjz8JaDDIr9f0q_rbZuiqgIt){target="_blank"}
- [Electrical and Mechanical Modifications for the Project](https://drive.google.com/open?id=15Fxa2cCJTmTctiDUJQCwhMFjNa4Zfk8-){target="_blank"}

You may notice that a lot of these previous topics are focused on Fourier Series and Transforms, those are important concepts that we expect you to pick up in E72.
If you'd like to brush up on them you can take a look at these videos:

- [Khan Academy on Fourier Series](https://www.khanacademy.org/science/electrical-engineering/ee-signals#ee-fourier-series){target="_blank"} (this is a sin/cos formulation rather than complex exponential, but it's a good introduction.  The visualization video is particularly helpful.)
- [David Dorran on the Discrete Fourier Transform](https://www.youtube.com/watch?v=h6QJLx22zrE){target="_blank"} (a quick introduction to thinking about this for sampled data with a link to a longer video at the end)
- [We have some prototype Fourier Videos](https://www.youtube.com/playlist?list=PLDA3QBjykWVxmUZvHMy7Qc9i1rltPq9IV){target="_blank"} (there are more topics we'd like to cover, but these are an OK place to start)
