---
title: "Lab 6 Writing Assignment"
subtitle: Technical Memo
---

## Introduction

In this writing assignment you will write a complete technical memorandum about Lab 6 that explains the experiments you undertook, your analysis, and your results. This assignment is summative and different than the previous writing assignments in this class for a few reasons:

1.  You are required to write a complete report instead of just focusing on a single section.
2.  No resubmits are allowed. This means you've got to get feedback on your own before submitting to make sure you do you best on the first submission!

You have all the pieces and tools you need to write this report and we look forward to seeing the way you put them all together!

Note that there are also fewer specific guidelines for this report. When in question, refer to the relevant writing assignments from previous labs for guidance on how to write a particular section. If you still have questions after doing that, please reach out to an instructor.

## Statement of Work

Write a full technical memorandum (report) about Lab 6 that describes the experiments you undertook, your analysis, and your results. This memo may be up to 5 pages long including references.

Be sure to include the following sections:

-   An abstract that concisely summarizes your main takeaway
-   An introduction that motivates the work and provides appropriate references
-   A methods and analysis section describing: 
    -   the experimental and computational methods you use
    -   relevant analytical models and their equations
-   A results and discussion section that:
    -   reports your experimental and computational data in captioned figures and tables (as appropriate)
    -   highlights key features of the figure or table in the body text
    -   describes the important quantitative takeaways
-   A conclusion which summarizes the important takeaways, sources of error, lessons learned, and describes areas for future work.
-   References in [IEEE format](./assets/IEEE%20Citation%20Guidelines.pdf)

You have leeway in the organization of this memo, and the scientific standard of Abstract, Introduction, Background & Methods, Results & Discussion, and Conclusion may or may not serve you well depending on your approach. Be sure to carefully select the appropriate topics to discuss so that your report fits in the page limit; the report won't have room to include every piece of data asked for in the submission sheet.

## Learning Objectives

By the end of this writing assignment you will...

-   Learn to write a full technical report that follows the conventions of scientific writing.
-   Reflect on and synthesize the skills that have been built through the previous writing assignments.

## Format Notes

Be mindful of tense and avoid use of the first person including saying “we” or “the team,” both of which count as first person because you are implying the presence of an experimenter.

## Resources

-   Refer to previous E80 writing assignments for guidelines on how to write high-quality versions of the various sections needed.
    -   [Lab 1: Figures and Captions](../lab1/writing.qmd)
    -   [Lab 2: Methods, Results, and Tables](../lab2/writing.qmd)
    -   [Lab 3: Electrical Schematics and Equations](../lab3/writing.qmd)
    -   [Lab 4: Introductions](../lab4/writing.qmd)
-   Short tech memo from Prof. Spjut ([link](https://drive.google.com/file/d/1wtEeyfcI0ObH-54Jn9V4pzgGdI38T4-9/view?pli=1))

## Rubric

Unlike the other writing assignments in this class which have been graded using effort and completion specifications, the final lab report will be graded using a traditional 0-100 scale using the following rubric.

+----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+
| Component            | Criteria                                                                                                                                                                | Points |
+======================+=========================================================================================================================================================================+========+
| Abstract             | -   Brief intent of the lab                                                                                                                                             | 9%     |
|                      | -   Contains summary of results and main takeaway                                                                                                                       |        |
+----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+
| Introduction         | -   Summarizes intent of lab and tasks taken to complete that intent.                                                                                                   | 13.5%  |
|                      | -   Contains relevant background information/references to help the reader understand the paper                                                                         |        |
|                      | -   Describes the forthcoming sections of the lab report, which demonstrates a well-planned report organization.                                                        |        |
+----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+
| Methods and Analysis | -   Provides a concise, easy-to-follow description of the materials and specific procedures used in the lab.                                                            | 9%     |
|                      | -   Describes the analytical models used to check the data.                                                                                                             |        |
+----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+
| Results              | -   Contains figures and tables that are appropriate to the data and are arranged in an order that best present the results.                                            | 13.5%  |
|                      | -   Includes descriptions of the figures and tables (referencing the appropriate methods if necessary) and interpretations of the contents of the figures and tables.   |        |
|                      | -   Clearly refers to the appropriate figures/tables in the paragraphs (Figure 1, Table 2, etc.).                                                                       |        |
+----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+
| Conclusion           | -   States what has been learned about underwater robotics from doing the experimental procedure.                                                                       | 13.5%  |
|                      | -   Describes anything else learned from doing the lab and writing the lab report (such as the lab procedure, methods of analyzing data, how to present results, etc.). |        |
|                      | -   Includes sources of error, ideas for future work                                                                                                                    |        |
+----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+
| References           | -   Includes all the sources used, such as the lab manual, the textbook, and any reference books or articles cited.                                                     | 9%     |
|                      | -   Uses the standard IEEE article format for citations and references.                                                                                                 |        |
+----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+
| Overall Writing      | -   Uses the appropriate formatting for figures and tables.                                                                                                             | 32.5%  |
|                      | -   Figures/tables are numbered, have concise captions, labeled axes, and have a legend where appropriate.                                                              |        |
|                      | -   Includes necessary headings and subheadings, but no more than that.                                                                                                 |        |
|                      | -   Correct sentence mechanics like cohesion and coherence between sentences and no run-ons                                                                             |        |
|                      | -   Correct paragraph mechanics like topic sentences and breaks between ideas                                                                                           |        |
|                      | -   Clear of spelling errors                                                                                                                                            |        |
|                      | -   No first person                                                                                                                                                     |        |
+----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+
