---
title: E80 Poster Session Agenda
---

The following document describes the agenda for the E80 poster session.

## Set Up Phase (4:00 – 4:15 pm)

1. Gather with your project team in the Outdoor Tents.  
2. Pick an ink pad color for your group’s poster stamps.
3. Make your personal name badge using the available supplies.
4. You will be handed a card (odd or even number).
5. Find a poster board location to display your poster.

## Presentation Phase I (4:15 – 4:45 pm)

1. Odd cards: remain at their poster  
2. Even cards: check out other posters  
   - You must visit and peer review at least three posters, one from each section  
   - You may not visit a poster that presently has three visitors  
3. Bell will ring every five minutes at which point you must rotate to a new poster.

## Presentation Phase II (4:45 – 5:15 pm)

Repeat Phase I with even and odd cards switching roles.
Even cards remain at their poster and odd cards visit others' posters.

## Clean Up Phase (5:15 – 5:30 pm)

1. Take down your poster  
2. Vote in poster contests:  
   - Student’s Choice Awards  
   - Instructor’s Choice Awards  
3. Complete the poster session reflection form