---
title: "High-Level Rubric for E80 Final Report"
toc: true
number-sections: true
format:
  html: default
  docx: default
---

## Overview

This rubric provides suggestions on the topics that each of your sections should address.

## Report Sections

### Abstract

The abstract articulates what was done, including a quick description of the experimental method. The abstract mentions quantitative conclusions.

### Introduction

The introduction motivates the work and explains experimental and modeling methods well enough to orient the reader to the paper.
The introduction does not explain technical details in more depth than necessary to orient the reader: those details belong in the main body.
A successful introduction motivates work, explains experimental and modeling methods well enough to orient the reader to the paper.

The introduction should also include an explanation of the specific phenomena the robot was designed to measure, why these measurements are important, and what can be learned from these measurements.
In particular, each goal of the project should be articulated.

### Sensor Design

A discussion of what sensors were chosen and how they relate to the scientific or engineering goals.
The discussion should address the sensor input/excitation range and how these compare with the expected excitation during deployment.
The discussion should also address the output range and or form (voltage, AC voltage or pulse train, pulse width modulated, pulse height modulated, etc.), and impedance.
This should include discussion of the component values which were selected or calculated (e.g., how did you map expected variations in output into the 0-to-3.3V input range of the Teensy.) 
This section should also explain if the sample rate of 10 Hz was sufficient along with any modifications to the robot which were made to ensure the sensor functioned properly (these may be in a separate mechanical design section). 

Successful sensor descriptions should include:
- Expected input limits articulated quantitatively and backed with analysis/simulation
- Complete schematics for every circuit designed.
- Circuit topology, gain and signal conditioning discussed for each sensor. 
- Power supplies and their uses enumerated. 
- Comparison of input limit to datasheet spec. 
- Discussion of output range and time constant for each sensor.
- Mechanical modifications considered and well described.

### Robot Design

This section should include information about the mechanical design and integration of your robot.
Discussion should include sensors placement and what considerations were made about the mechanical aspects of the design (e.g., buoyancy and balance calculations)

### Results and Deployment Details

This section should include:

- An explanation of how MATLAB, historical data, or your own models were used to predict the robot’s performance, the sensor measurements versus time, and how the modeling results informed the experimental protocol.
- An explanation of the experimental protocol. (e.g., The goals for each deployment, prepping the robot, starting the teensy code, deployment details, recovery details, retrieval of the data, and processing of the data.)
- Processed data and plotted figures from your deployments along with discussion about the results and what they mean.
- A discussion of deployment safety.
- A comparison of the modeled (or expected) data from with the retrieved data from. Graphical comparison is preferred, but written comparison should be used as appropriate, especially to explain the graphical data. Error bars or estimates should be included in all experimental quantities. Whether each deployment is compared individually or all deployments compared together will depend on the data sets and the results. Descriptions of the degree of agreement should be made and possible explanations of the discrepancies should be present.


### Conclusion 
The conclusions should not be just a summary, but should be a summation of lessons learned, both about the process and of the comparison of the data and models. 
It should answer the question, “What does it all mean?”
It should include recommendations for future work and/or future versions of the class.

### Acknowledgements

List all non E80 personnel who helped. Be sure to briefly describe their contribution.

### References 
List and cite all relevant references. Be especially careful to cite sources for figures that you have not drawn yourself.

### English usage 

**Grammar**: Free of spelling, capitalization, and usage errors. Few, if any, errors in punctuation. Sophisticated and consistent command of standard English.

**Transitions:** Ideas/paragraphs/sections are connected by effective transition words and phrases.Precise, interesting, and accurate word choice. Writing style enhances readability of writing.

**Focus:** Language choices (degree of jargon) and use of background material reflect attention to audience. Writing has a clear, distinct focus.

**Organization:** Generally well-developed ideas have a logical flow. Introductory and closing material is used effectively. Piece has a sense of completeness.

**Elaboration / Support:** Each main idea is supported by detailed data or reasoning. All details are related to topic. Complete, correct documentation of a wide variety of sources.
